name: CI

on:
  push:
    branches:
      - master
      - feature/ci-cd

  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build Docker containers
        run: docker compose build

      - name: Install Composer dependencies
        run: docker compose run --rm php composer install --no-interaction --prefer-dist

      - name: Start Docker containers
        run: docker compose up -d

      - name: Check Docker containers
        run: docker compose ps

      - name: Check PHP version
        run: docker compose exec -T php php -v

      - name: Run Laravel tests
        run: docker compose exec -T php php artisan test

      - name: Stop Docker containers
        if: always()
        run: docker compose down
