name: CI

on:
  push:
    branches:
      - master
      - feature/ci-cd

  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Show project information
        run: |
          echo "CI is running"
          echo "Current directory:"
          pwd
          echo "Project files:"
          ls -la
